swagger: "2.0"
info:
  description: |
    Uma api que recebe uma palavra e uma lista de urls e retorna o número de ocorrencias daquela palavra em cada url.
  version: "0.0.1"
  title: Keyword Finder
  contact:
    name: rafaellcoellho@gmail.com
basePath: /
schemes:
  - http
paths:
  /:
    post:
      tags:
        - Crawler
      description: Conta o número de ocorrencias de uma palavra em urls
      operationId: crawler
      consumes:
        - application/json
      produces:
        - application/json
      parameters: 
        - in: body
          name: body
          description: Teste
          required: true
          schema:
            type: object
            properties:
              word:
                type: string
              urls:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: Sucesso. Retorna json com os resultados
          schema:
            type: object
            additionalProperties:
              type: string
            example: {"google.com": "2"}
        "405":
            description: Método Http inválido
        "500":
            description: Erro interno
  /alive:
    get:     
      tags:
      - Testes 
      description: Testar se o serviço está funcionando
      produces:
      - text/plain
      responses:
        "200":
            description: Está funcionando. Retorna "RUNNING"
        "405":
            description: Método Http inválido